name: Publish to PyPI

on:
  release:
    types: [published]


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Get release tag
        id: get_tag
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Update version
        run: |
          sed -i "s/version = .*/version = \"${{ steps.get_tag.outputs.RELEASE_TAG }}\"/" pyproject.toml
      - name: Build wheel
        run: |
          pip wheel . --no-deps -w deploy

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: deploy/
          if-no-files-found: error

      - name: Publish on PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: deploy/
